/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FocusIndexRouteImport } from './routes/focus/index'
import { Route as FocusStatsRouteImport } from './routes/focus/stats'
import { Route as FocusHistoryRouteImport } from './routes/focus/history'

const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusIndexRoute = FocusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FocusRoute,
} as any)
const FocusStatsRoute = FocusStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => FocusRoute,
} as any)
const FocusHistoryRoute = FocusHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => FocusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/focus': typeof FocusRouteWithChildren
  '/focus/history': typeof FocusHistoryRoute
  '/focus/stats': typeof FocusStatsRoute
  '/focus/': typeof FocusIndexRoute
}
export interface FileRoutesByTo {
  '/focus/history': typeof FocusHistoryRoute
  '/focus/stats': typeof FocusStatsRoute
  '/focus': typeof FocusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/focus': typeof FocusRouteWithChildren
  '/focus/history': typeof FocusHistoryRoute
  '/focus/stats': typeof FocusStatsRoute
  '/focus/': typeof FocusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/focus' | '/focus/history' | '/focus/stats' | '/focus/'
  fileRoutesByTo: FileRoutesByTo
  to: '/focus/history' | '/focus/stats' | '/focus'
  id: '__root__' | '/focus' | '/focus/history' | '/focus/stats' | '/focus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FocusRoute: typeof FocusRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/': {
      id: '/focus/'
      path: '/'
      fullPath: '/focus/'
      preLoaderRoute: typeof FocusIndexRouteImport
      parentRoute: typeof FocusRoute
    }
    '/focus/stats': {
      id: '/focus/stats'
      path: '/stats'
      fullPath: '/focus/stats'
      preLoaderRoute: typeof FocusStatsRouteImport
      parentRoute: typeof FocusRoute
    }
    '/focus/history': {
      id: '/focus/history'
      path: '/history'
      fullPath: '/focus/history'
      preLoaderRoute: typeof FocusHistoryRouteImport
      parentRoute: typeof FocusRoute
    }
  }
}

interface FocusRouteChildren {
  FocusHistoryRoute: typeof FocusHistoryRoute
  FocusStatsRoute: typeof FocusStatsRoute
  FocusIndexRoute: typeof FocusIndexRoute
}

const FocusRouteChildren: FocusRouteChildren = {
  FocusHistoryRoute: FocusHistoryRoute,
  FocusStatsRoute: FocusStatsRoute,
  FocusIndexRoute: FocusIndexRoute,
}

const FocusRouteWithChildren = FocusRoute._addFileChildren(FocusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FocusRoute: FocusRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
